logging:
  level:
    org.springframework.cloud: TRACE
    org.apache.sshd: TRACE
server:
  port: 8889
spring:
  cloud:
    refresh:
      enabled: false
    config:
      server:
        git:
          cloneOnStart: true
          uri: https://github.com/spring-cloud-samples/spring-cloud-intro-demo-config

