logging:
  level:
    org.springframework.cloud: TRACE
server:
  port: 8889
spring:
  security:
    user:
      name: root
      password: password
  cloud:
    refresh:
      enabled: false
    config:
      server:
        git:
          cloneOnStart: false
          uri: https://github.com/spring-cloud-samples/spring-cloud-intro-demo-config

#encrypt:
#  key: asdfajazdfjalasdfasdf
