logging:
  level:
    org.springframework.cloud: TRACE
    org.apache.sshd: TRACE
server:
  port: 8889
spring:
  security:
    user:
      name: root
      password: password
  cloud:
    refresh:
      enabled: false
    config:
      server:
        git:
          cloneOnStart: true
          uri: git@github.com:OlgaMaciaszek/spring-cloud-intro-demo-config.git

encrypt:
  key: asdfajazdfjalasdfasdf
